/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toCook.view;

import java.awt.Color;
import java.time.LocalTime;
import javax.swing.JFrame;
import toCook.DAO.DiffusionDAO;
import toCook.model.Diffusion;

/**
 *
 * @author a.hammerlin
 */
public class modif extends javax.swing.JFrame {

    
    protected int id;
    /**
     * Creates new form modif
     */
    public modif(int id) {
        this.id = id;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        Color col=new Color(255,199,199);
        getContentPane().setBackground(col);
        
        Diffusion diffusion = DiffusionDAO.getLaDiffusion(id);
       
        this.entree_date.setText(diffusion.getLeJour().toString());
        this.entree_hdebut.setText(diffusion.getHoraire());
        this.entree_categoriecsa.setText(diffusion.getLeProgramme().getLaCategorieCSA().getCode());
        this.entree_duree.setText(Integer.toString(diffusion.getLeProgramme().getDuree()));
        this.entree_titre.setText(diffusion.getLeProgramme().getEmission().getTitre() + " " + diffusion.getLeProgramme().getTitre());
        this.entree_origine.setText(diffusion.getLeProgramme().getEmission().getOrigine());
        this.entree_genre.setText(diffusion.getLeProgramme().getEmission().getGenre());
        
        this.entree_hfin.setText((LocalTime.parse(diffusion.getHoraire()).plusMinutes(diffusion.getLeProgramme().getDuree())).toString());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre_modif = new javax.swing.JLabel();
        duree_modif = new javax.swing.JLabel();
        origine_modif = new javax.swing.JLabel();
        top = new javax.swing.JLabel();
        entree_duree = new javax.swing.JTextField();
        entree_titre = new javax.swing.JTextField();
        entree_origine = new javax.swing.JTextField();
        annuler = new javax.swing.JButton();
        intervenant_modif = new javax.swing.JLabel();
        entree_intervenant = new javax.swing.JTextField();
        genre_modif = new javax.swing.JLabel();
        entree_genre = new javax.swing.JTextField();
        categoriecsa_modif = new javax.swing.JLabel();
        entree_categoriecsa = new javax.swing.JTextField();
        paneau_haut = new javax.swing.JPanel();
        date_modif = new javax.swing.JLabel();
        entree_date = new javax.swing.JTextField();
        hdebut_modif = new javax.swing.JLabel();
        entree_hdebut = new javax.swing.JTextField();
        hfin_modif = new javax.swing.JLabel();
        entree_hfin = new javax.swing.JTextField();
        categoriecsa_modif1 = new javax.swing.JLabel();
        entree_categoriecsa1 = new javax.swing.JTextField();
        categoriecsa_modif2 = new javax.swing.JLabel();
        direct_entree = new javax.swing.JComboBox<>();
        categoriecsa_modif3 = new javax.swing.JLabel();
        direct_entree1 = new javax.swing.JComboBox<>();
        enregistrer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));

        titre_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        titre_modif.setText("Titre :");

        duree_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        duree_modif.setText("Duree :");

        origine_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        origine_modif.setText("Origine :");

        top.setFont(new java.awt.Font("ASimpleLife", 1, 18)); // NOI18N
        top.setText("Modification du programme");

        entree_duree.setToolTipText("");
        entree_duree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_dureeActionPerformed(evt);
            }
        });

        entree_titre.setToolTipText("");
        entree_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_titreActionPerformed(evt);
            }
        });

        entree_origine.setToolTipText("");
        entree_origine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_origineActionPerformed(evt);
            }
        });

        annuler.setFont(new java.awt.Font("ASimpleLife", 1, 12)); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorderPainted(false);
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        intervenant_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        intervenant_modif.setText("Intervenant :");

        entree_intervenant.setToolTipText("");
        entree_intervenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_intervenantActionPerformed(evt);
            }
        });

        genre_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        genre_modif.setText("Genre :");

        entree_genre.setToolTipText("");
        entree_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_genreActionPerformed(evt);
            }
        });

        categoriecsa_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        categoriecsa_modif.setText("Categorie CSA");

        entree_categoriecsa.setToolTipText("");
        entree_categoriecsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_categoriecsaActionPerformed(evt);
            }
        });

        paneau_haut.setBackground(new java.awt.Color(255, 148, 148));

        date_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        date_modif.setText("Date");

        entree_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_dateActionPerformed(evt);
            }
        });

        hdebut_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        hdebut_modif.setText("Heure debut");

        entree_hdebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_hdebutActionPerformed(evt);
            }
        });

        hfin_modif.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        hfin_modif.setText("Heure fin");

        javax.swing.GroupLayout paneau_hautLayout = new javax.swing.GroupLayout(paneau_haut);
        paneau_haut.setLayout(paneau_hautLayout);
        paneau_hautLayout.setHorizontalGroup(
            paneau_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneau_hautLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_modif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entree_date, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(hdebut_modif)
                .addGap(18, 18, 18)
                .addComponent(entree_hdebut, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(hfin_modif)
                .addGap(18, 18, 18)
                .addComponent(entree_hfin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        paneau_hautLayout.setVerticalGroup(
            paneau_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneau_hautLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(paneau_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_modif)
                    .addComponent(entree_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hdebut_modif)
                    .addComponent(entree_hdebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hfin_modif)
                    .addComponent(entree_hfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        categoriecsa_modif1.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        categoriecsa_modif1.setText("Lien Image");

        entree_categoriecsa1.setToolTipText("");
        entree_categoriecsa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entree_categoriecsa1ActionPerformed(evt);
            }
        });

        categoriecsa_modif2.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        categoriecsa_modif2.setText("En direct ?");

        direct_entree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oui", "Non" }));
        direct_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direct_entreeActionPerformed(evt);
            }
        });

        categoriecsa_modif3.setFont(new java.awt.Font("ASimpleLife", 1, 14)); // NOI18N
        categoriecsa_modif3.setText("Programme culinaire");

        direct_entree1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oui", "Non" }));
        direct_entree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direct_entree1ActionPerformed(evt);
            }
        });

        enregistrer1.setFont(new java.awt.Font("ASimpleLife", 1, 12)); // NOI18N
        enregistrer1.setText("Enregistrer");
        enregistrer1.setBorderPainted(false);
        enregistrer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(top))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titre_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paneau_haut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(duree_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_duree, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origine_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_origine, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intervenant_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_intervenant, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoriecsa_modif1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_categoriecsa1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genre_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoriecsa_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entree_categoriecsa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoriecsa_modif2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(direct_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(annuler)
                                    .addComponent(categoriecsa_modif3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(direct_entree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(enregistrer1)
                                        .addGap(86, 86, 86)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(top)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneau_haut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titre_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entree_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duree_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entree_duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origine_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entree_origine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intervenant_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entree_intervenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genre_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entree_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entree_categoriecsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriecsa_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoriecsa_modif1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entree_categoriecsa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriecsa_modif2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direct_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriecsa_modif3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direct_entree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrer1)
                    .addComponent(annuler))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entree_dureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_dureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_dureeActionPerformed

    private void entree_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_titreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_titreActionPerformed

    private void entree_origineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_origineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_origineActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void entree_intervenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_intervenantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_intervenantActionPerformed

    private void entree_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_dateActionPerformed

    private void entree_hdebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_hdebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_hdebutActionPerformed

    private void entree_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_genreActionPerformed

    private void entree_categoriecsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_categoriecsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_categoriecsaActionPerformed

    private void entree_categoriecsa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entree_categoriecsa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entree_categoriecsa1ActionPerformed

    private void direct_entreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direct_entreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direct_entreeActionPerformed

    private void direct_entree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direct_entree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direct_entree1ActionPerformed

    private void enregistrer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel categoriecsa_modif;
    private javax.swing.JLabel categoriecsa_modif1;
    private javax.swing.JLabel categoriecsa_modif2;
    private javax.swing.JLabel categoriecsa_modif3;
    private javax.swing.JLabel date_modif;
    private javax.swing.JComboBox<String> direct_entree;
    private javax.swing.JComboBox<String> direct_entree1;
    private javax.swing.JLabel duree_modif;
    private javax.swing.JButton enregistrer1;
    private javax.swing.JTextField entree_categoriecsa;
    private javax.swing.JTextField entree_categoriecsa1;
    private javax.swing.JTextField entree_date;
    private javax.swing.JTextField entree_duree;
    private javax.swing.JTextField entree_genre;
    private javax.swing.JTextField entree_hdebut;
    private javax.swing.JTextField entree_hfin;
    private javax.swing.JTextField entree_intervenant;
    private javax.swing.JTextField entree_origine;
    private javax.swing.JTextField entree_titre;
    private javax.swing.JLabel genre_modif;
    private javax.swing.JLabel hdebut_modif;
    private javax.swing.JLabel hfin_modif;
    private javax.swing.JLabel intervenant_modif;
    private javax.swing.JLabel origine_modif;
    private javax.swing.JPanel paneau_haut;
    private javax.swing.JLabel titre_modif;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
